# Generated by Django 3.1 on 2020-09-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0002_product_b_id'),
        ('Client', '0003_customer_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_product',
            new_name='CustomerProduct',
        ),
    ]
