# Generated by Django 3.1 on 2020-09-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('PetShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.bill'),
        ),
    ]
