# Generated by Django 3.1 on 2020-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_Name', models.CharField(max_length=100)),
                ('s_Cost', models.FloatField(blank=True)),
                ('s_type', models.CharField(max_length=20)),
            ],
        ),
    ]
